# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
       ndk-version: r21e
       add-to-path: false
    - run: ./build.sh
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }} 
    - name: Build
      run: go get fyne.io/fyne/v2@latest
           go get fyne.io/fyne/app
           go get fyne.io/fyne/container
           go get fyne.io/fyne/widget
           fyne package -os android -appID com.oashalal.app

    - name: Upload built apk file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: app.apk
